### ISSUE TITLE
How can we start the flexrayusbinterface?

### ISSUE THREAD

**Issue by compiaffe** [Roboy/ros_control#13]
flexrayusbinterface is installed as part of roboy_ros_control:

Assuming you have added yourself to the dialout group:
`sudo usermod -a -G dialout *your-username*`

and you have sourced the new ros jade:
`source /opt/ros/jade/setup.bash`

you should be able to start it with 
`rosrun flexrayusbinterface flexrayusbinterface `

If this complains about not finding a roscore (the dependency will likely be taken out in the future) start a roscore beforehand and keep it running:
`roscore`

**Comment by letrend** [comment]
Out dated
